stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: package/Dockerfile.multistage
      buildContext: .
      tag: rawmind/hello-world-app:${CICD_GIT_TAG}
      registry: 127.0.0.1:34827
    when:
      event:
        include:
        - tag
- name: Deliver
  steps:
  - runScriptConfig:
      image: golang:1.12.13-alpine
      shellScript: |-
        apk add --upgrade --no-cache git make bash
        make k8s_manifests
    env:
      VERSION: $(sh scripts/version)
    when:
      event:
        include:
        - tag
- name: Deploy
  steps:
  - applyYamlConfig:
      path: k8s/hello-world-app-app.yaml
    when:
      event:
        include:
        - tag
timeout: 60
notification: {}
