stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: package/Dockerfile.multistage
      buildContext: .
      tag: rawmind/hello-world-app:$(sh scripts/version)
      registry: 127.0.0.1:34827
- name: Deliver
  steps:
  - runScriptConfig:
      image: golang:1.12.13-alpine
      shellScript: |-
        apk add --upgrade --no-cache git make bash
        make k8s_manifests
    env:
      VERSION: $(sh scripts/version)
  - applyYamlConfig:
      path: k8s/hello-world-app-deployment.yaml
timeout: 60
notification: {}
