stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: package/Dockerfile.multistage
      buildContext: .
      tag: rawmind/hello-world-app
      registry: 127.0.0.1:34410
timeout: 60
notification: {}
